language: node_js

env:
  global:
    # Sauce Labs are OK with this and it is currently necessary to expose this information for testing pull requests;
    # please get your own free key if you want to test yourself
    - SAUCE_USERNAME=fxa-client
    - SAUCE_ACCESS_KEY=863203af-38fd-4f1d-9332-adc8f60f157b

sudo: false

notifications:
  irc:
    channels:
      - "irc.mozilla.org#fxa-bots"
    use_notice: false
    skip_join: false
    on_success: change
    on_failure: change

node_js:
  - "0.10"

before_install:
  # Update to latest npm 2
  - npm install -g npm@2

# blacklist
branches:
  except:
    - release
    - /^.*-docs$/

script:
  - grunt travis
  - npm run test-extras
